import Head from 'next/head';
import Header from '../componets/Header/index';
import styles from '../styles/Home.module.css'
import Carrocel from '../components/Carrocel/index'
import Condominios from '@/components/Condominios';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <Header />
        <Carrocel/>
        <section className={styles.sobre}>
          
          <div className={styles.texto}>
          <h1>Estamos Localizados</h1>
          <h2>Proximo da ...</h2>
          <p>Na rua Jose, Bairro Centro</p>
          <p>Braço do Norte</p>
          </div>
        </section>
        <Condominios/>
        <Footer/>
      </main>
    </>
  );
}
